# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/44444444-4444-4444-8888-888888888888";
      fsType = "ext4";
    };

fileSystems."/home" = {
    device = "/dev/disk/by-uuid/fc205b9f-b1cb-40af-8ea7-59f9e88fbbd9";
    fsType = "ext4";
};
#fileSystems."/media/SSD1GB" =
#    { device = "/dev/disk/by-uuid/8e97e9d3-ec0b-4426-8627-8f994e2f94c2";
#      fsType = "ext4";
#    };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
